### ISSUE TITLE
Regarding Code

### ISSUE THREAD

**Issue by lirus7** [guanjz20/StyleSync#1]
Hey! Thanks for the fantastic work. 
I am waiting to try it out. Can I have an estimate on when the code will be released?

**Comment by caopulan** [comment]
same question

**Comment by boxicon** [comment]
Same question! Cant wait to test this!

**Comment by guanjz20** [comment]
Working on it! You can watch this repo and stay tuned.

**Comment by boxicon** [comment]
> Working on it! You can watch this repo and stay tuned.

You maybe know any date? Thanks for your answer!

**Comment by guanjz20** [comment]
Issue merged.

**Comment by guanjz20** [comment]
Issue merged, find #3 .
